// Auto-generated by OpenLane
module timer_pwm_interface(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[4:0] addr,
  input[7:0] wdata,
  input write_en,
  input read_en,
  output[7:0] rdata,
  output outa,
  output outb,
  output irq_timer
);
endmodule
